### ISSUE TITLE
Upload button on start page does not work

### ISSUE THREAD

**Issue by Newbie859** [AlfHou/hammond#116]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base yes

**Describe the bug**
No action on click on 'Upload file'.

**To Reproduce**
1. Login to you Hammond
2. Click on 'Upload file'

**Expected behavior**
Upload prompt / page appears.

**Screenshots**
<img width="833" alt="image" src="https://github.com/user-attachments/assets/fa6f71a4-9da1-4bea-8212-be707018b589">

**Additional context**
Hey AlfHou, I appreciate your work and the really simple and helpful application. And I am excited to see new features like mentioned in your roadmap, especially regarding servicing. Best regards from Germany

**Comment by Goloso98** [comment]
I agree, its not the most intuitive UI, from what we are used to on other sites. But, you should click on upload photo (and choose one) and then upload file.
If you have any problem leave an update.

**Comment by Newbie859** [comment]
Understood. Functionality is there. It is maybe unlucky described or the buttons named. For me it is fine now that I know how to actually use both buttons. Thank you. Issue closed 👍
