### ISSUE TITLE
Year of manufacture duplicated 

### ISSUE THREAD

**Issue by marc115uk** [AlfHou/hammond#21]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base yes

**Describe the bug**
When adding a vehicle year of manufacture is duplicated, I believe on the original version this was engine size 

![Untitled](https://user-images.githubusercontent.com/57296217/215295377-828bf2ba-908a-4c7a-860d-cdd86cf4e50c.jpg)

**Comment by AlfHou** [comment]
Related to #16. This is fixed in #24
