### ISSUE TITLE
Is this version of hammond being published anywhere I can install it from?

### ISSUE THREAD

**Issue by RobbieLD** [AlfHou/hammond#35]
I've been using the old version (from which this was forked) but I see this new version is under active development and I've love to change over and also help with development. So I was just wondering if it's being built and pushed to dockerhub?

**Comment by rlewis187** [comment]
It has, theres a discussion on it here:
https://github.com/AlfHou/hammond/discussions/6

**Comment by AlfHou** [comment]
Hi! It's being published to docker hub under alfhou/hammond  as @rlewis187 mentioned :) Let me know if you experience any trouble migrating.

**Comment by RobbieLD** [comment]
Thanks very much @rlewis187 and @AlfHou
