### ISSUE TITLE
Creating new user with role of 'test/test'

### ISSUE THREAD

**Issue by chriscn** [AlfHou/hammond#39]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base yes

**Describe the bug**
![Screenshot 2023-02-13 at 12 56 31](https://user-images.githubusercontent.com/25829276/218464186-a1549df0-f354-414b-917a-d0258f93189a.png)

**Expected behavior**
Clearly defined roles, the ones I would image are:
- ADMIN: Full access
- Manager: Add / remove / manage vehicles
- Write: Write details about cars
- Read: only read

**Screenshots**

**Additional context**

**Comment by AlfHou** [comment]
This will be fixed in the next release which I'll most likely push next week. It's related to some translation errors. Existing roles are currently: Admin and user. The first role in the dropdown is admin, the second one is user.
