### ISSUE TITLE
Feature: Generic Fillup Import

### ISSUE THREAD

**Issue by alienp4nda** [AlfHou/hammond#48]
I would like to provide a means to import csv, maybe even json, that allows the user to select which field from their import corresponds to the Hammond field.

I believe this would help solve #46 and #42 since the users will be able to map the fields in the UI.

![Screen Shot 2023-04-15 at 7 40 54 AM](https://user-images.githubusercontent.com/14863348/232227628-d5f6bc5b-944a-4afc-a702-b13b1ee45505.png)
![Screen Shot 2023-04-15 at 7 41 06 AM](https://user-images.githubusercontent.com/14863348/232227633-2abbd2d5-f497-443b-a52e-7f2922c0439e.png)

**Comment by AlfHou** [comment]
That sounds like a great idea! Let me know if I can assist with anything :)

**Comment by alienp4nda** [comment]
Much appreciated, I will let you know.

**Comment by alienp4nda** [comment]
I've finished with the csv fillup import, as in it's functional.  Would y'all mind testing with your own data?

**Comment by AlfHou** [comment]
Great progress. I'm getting an error 
![image](https://user-images.githubusercontent.com/20001253/232887767-69fa0c27-3be2-40a0-a67e-074487db869c.png)
. Tried debugging a bit, and seems like the backend is only receiving '0' for most many properties. See attached file: 
[DRIVVO_HONDA_CB400N.csv](https://github.com/AlfHou/hammond/files/11265787/DRIVVO_HONDA_CB400N.csv)

**Comment by alienp4nda** [comment]
Fixed it.  There was an if statement with the wrong logic.  Definitely no more coding when I'm tired!

**Comment by AlfHou** [comment]
Work for my Drivvo files. I don't have any other files to test it on, and I don't think we can expect others to set up a dev environment to test it. I suggest you open a PR and I'll review it, and then people can rather just report bugs if they experience them. 😃

**Comment by alienp4nda** [comment]
Let me change some of the wording so it clearly states it's only for
fillups and only csv.  I'll be starting on the expense import soon.

On 4/21/23, Alf Sebastian Houge ***@***.***> wrote:
> Work for my Drivvo files. I don't have any other files to test it on, and I
> don't think we can expect others to set up a dev environment to test it. I
> suggest you open a PR and I'll review it, and then people can rather just
> report bugs if they experience them. 😃
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/AlfHou/hammond/issues/48#issuecomment-1518221388
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
Respectfully,
Alex Hess
