### ISSUE TITLE
Docker image for v0.0.4

### ISSUE THREAD

**Issue by djjudas21** [AlfHou/hammond#57]
*Before creating a bug report please make sure you are using the latest docker image / code base.*

**Please complete the following information**
 - Installation Type: Docker
 - Have you tried using the latest docker image / code base: yes

**Describe the bug**
Thanks for releasing v0.0.4 :+1: I noticed that the Docker image tag `v0.0.4` isn't available on Docker Hub, and it's because the image has failed to build: https://github.com/AlfHou/hammond/actions/runs/5592418036

I don't know anything about npm but hopefully it's just something to do with the dependency resolution

**Comment by AlfHou** [comment]
Yup, I'm looking into it. I'll try to get it out by the end of today (GMT+2)

**Comment by AlfHou** [comment]
Should be solved in v0.0.21 (it took a lot of attempts 😝)

**Comment by djjudas21** [comment]
Yes, I saw all the pipelines! Thanks for your effort :+1: I have just updated my Helm chart to reference v0.0.21 https://github.com/djjudas21/charts/tree/main/charts/hammond
