### ISSUE TITLE
New translation - Slovenian, please add

### ISSUE THREAD

**Issue by thehijacker** [AlfHou/hammond#92]
Hello,

Just finished Slovenian translation. Can you please add it to the next release.

Thank you.

[sl.json](https://github.com/AlfHou/hammond/files/13849892/sl.json)

**Comment by alienp4nda** [comment]
Make a PR with the file added

**Comment by thehijacker** [comment]
Done. I hope I did it right.

**Comment by thehijacker** [comment]
I can see new docker image, but without my translation PR. Can you also merge it and publish new image?

**Comment by alienp4nda** [comment]
Image is currently being built.

**Comment by alienp4nda** [comment]
The new image is out.

**Comment by thehijacker** [comment]
Looks great. Thank you.
